//
//  WorldCupYear.swift
//  WorldCapp
//
//  Created by Maks Vogtman on 04/05/2023.
//

import Foundation
import UIKit

struct WorldCupYear {
    let year: String
    let numberOfTeams: String
    let homeFlagImage: UIImage?
    let visitorFlagImage: UIImage?
    let thirdPlaceFlagImage: UIImage?
    let fourthPlaceFlagImage: UIImage?
    let finalDescription: String
    let thirdPlaceDescription: String
    let topScorer: String
    let mvp: String
    let goldenGlove: String
    let finalLabelText: String
    let thirdPlaceLabelText: String
    let versus: String
    let secondVersus: String
}


struct EventData {
    static let events = [
        WorldCupYear(year: "1930 🇺🇾", numberOfTeams: "13 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "uruguay")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "argentina")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "usa")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "yugoslavia 1")!), finalDescription: "Uruguay🥇 - Argentina🥈 4:2", thirdPlaceDescription: "There was no third place match", topScorer: "Golden Boot: Guillermo Stábile 🇦🇷 8 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1934 🇮🇹", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 1")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "czech republic")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 1")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "austria")!), finalDescription: "Italy🥇 - Czechoslovakia🥈 2:1 (a.e.t)", thirdPlaceDescription: "Germany🥉 - Austria 3:2", topScorer: "Golden Boot: Oldřich Nejedlý 🇨🇿 5 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1938 🇫🇷", numberOfTeams: "15 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 1")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "hungary")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "sweden")!), finalDescription: "Italy🥇 - Hungary🥈 4:2", thirdPlaceDescription: "Brazil🥉 - Sweden 4:2", topScorer: "Golden Boot: Leônidas 🇧🇷 7 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1942 & 1946", numberOfTeams: "", homeFlagImage: UIImage(), visitorFlagImage: UIImage(), thirdPlaceFlagImage: UIImage(), fourthPlaceFlagImage: UIImage(), finalDescription: "Not held because of World War II", thirdPlaceDescription: "", topScorer: "", mvp: "", goldenGlove: "", finalLabelText: "", thirdPlaceLabelText: "", versus: "", secondVersus: ""),
        
        WorldCupYear(year: "1950 🇧🇷", numberOfTeams: "13 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "uruguay")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "sweden")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "spain 1")!), finalDescription: "Uruguay🥇 - Brazil🥈 2:1", thirdPlaceDescription: "Sweden🥉 - Spain 3:1", topScorer: "Golden Boot: Ademir 🇧🇷 8 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1954 🇨🇭", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "hungary")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "austria")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "uruguay")!), finalDescription: "West Germany🥇 - Hungary🥈 3:2", thirdPlaceDescription: "Austria🥉 - Uruguay 3:1", topScorer: "Golden Boot: Sándor Kocsis 🇭🇺 11 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1958 🇸🇪", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "sweden")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "france")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), finalDescription: "Brazil🥇 - Sweden🥈 5:2", thirdPlaceDescription: "France🥉 - West Germany 6:3", topScorer: "Golden Boot: Just Fontaine 🇫🇷 13 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1962 🇨🇱", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "czech republic")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "chile")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "yugoslavia 2")!), finalDescription: "Brazil🥇 - Czechoslovakia🥈 3:1", thirdPlaceDescription: "Chile🥉 - Yugoslavia 1:0", topScorer: "Golden Boot: 6 players has scored 4 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1966 🏴󠁧󠁢󠁥󠁮󠁧󠁿", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "england")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "portugal")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "soviet union")!), finalDescription: "England🥇 - West Germany🥈 4:2 (a.e.t)", thirdPlaceDescription: "Portugal🥉 - Soviet Union 2:1", topScorer: "Golden Boot: Eusébio 🇵🇹 9 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1970 🇲🇽", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 2")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "uruguay")!), finalDescription: "Brazil🥇 - Italy🥈 4:1", thirdPlaceDescription: "West Germany🥉 - Uruguay 1:0", topScorer: "Golden Boot: Gerd Müller 🇩🇪 10 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1974 🇩🇪", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "netherlands")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "poland")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), finalDescription: "West Germany🥇 - Netherlands🥈 2:1", thirdPlaceDescription: "Poland🥉 - Brazil 1:0", topScorer: "Golden Boot: Grzegorz Lato 🇵🇱 7 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1978 🇦🇷", numberOfTeams: "16 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "argentina")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "netherlands")!), thirdPlaceFlagImage:UIImage.imageWithBorder(from:  UIImage(named: "brazil")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 2")!), finalDescription: "Argentina🥇 - Netherlands🥈 3:1 (a.e.t)", thirdPlaceDescription: "Brazil🥉 - Italy 2:1", topScorer: "Golden Boot: Mario Kempes 🇦🇷 6 goals", mvp: "Golden Ball: Not awarded until 1982", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1982 🇪🇸", numberOfTeams: "24 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 2")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "poland")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "france")!), finalDescription: "Italy🥇 - Germany🥈 3:1", thirdPlaceDescription: "Poland🥉 - France 3:2", topScorer: "Golden Boot: Paolo Rossi 🇮🇹 6 goals", mvp: "Golden Ball: Paolo Rossi 🇮🇹", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1986 🇲🇽", numberOfTeams: "24 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "argentina")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "france")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "belgium")!), finalDescription: "Argentina🥇 - West Germany🥈 3:2", thirdPlaceDescription: "France🥉 - Belgium 4:2 (a.e.t)", topScorer: "Golden Boot: Gary Lineker 🏴󠁧󠁢󠁥󠁮󠁧󠁿 6 goals", mvp: "Golden Ball: Diego Maradona 🇦🇷", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1990 🇮🇹", numberOfTeams: "24 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "argentina")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 2")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "england")!), finalDescription: "West Germany🥇 - Argentina🥈 1:0", thirdPlaceDescription: "Italy🥉 - Englad 2:1", topScorer: "Golden Boot: Salvatore Schillaci 🇮🇹 6 goals", mvp: "Golden Ball: Salvatore Schillaci 🇮🇹", goldenGlove: "Golden Glove: Not awarded until 1994", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1994 🇺🇸", numberOfTeams: "24 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 2")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "sweden")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "bulgaria")!), finalDescription: "Brazil🥇 - Italy🥈 0:0 (a.e.t) (3-2 p.)", thirdPlaceDescription: "Sweden🥉 - Bulgaria 4:0", topScorer: "Golden Boot: Christo Stoichkov 🇧🇬 & Oleg Salenko 🇷🇺 6 goals", mvp: "Golden Ball: Romário 🇧🇷", goldenGlove: "Golden Glove: Michel Preud'homme 🇧🇪", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "1998 🇫🇷", numberOfTeams: "32 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "france")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "croatia")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "netherlands")!), finalDescription: "France🥇 - Brazil🥈 3:0", thirdPlaceDescription: "Croatia🥉 - Netherlands 2:1", topScorer: "Golden Boot: Davor Šuker 🇭🇷 6 goals", mvp: "Golden Ball: Ronaldo 🇧🇷", goldenGlove: "Golden Glove: Fabien Barthez 🇫🇷", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "2002 🇰🇷 & 🇯🇵", numberOfTeams: "32 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "turkey")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "south korea")!), finalDescription: "Brazil🥇 - Germany🥈 2:0", thirdPlaceDescription: "Turkey🥉 - South Korea 3:2", topScorer: "Golden Boot: Ronaldo 🇧🇷 8 goals", mvp: "Golden Ball: Oliver Kahn 🇩🇪", goldenGlove: "Golden Glove: Oliver Kahn 🇩🇪", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "2006 🇩🇪", numberOfTeams: "32 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "italy 2")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "france")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "portugal")!), finalDescription: "Italy🥇 - France🥈 1:1 (a.e.t) (5-3 p.)", thirdPlaceDescription: "Germany🥉 - Portugal 3:1", topScorer: "Golden Boot: Miroslav Klose 🇩🇪 5 goals", mvp: "Golden Ball: Zinedine Zidane 🇫🇷", goldenGlove: "Golden Glove: Gianluigi Buffon 🇮🇹", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "2010 🇿🇦", numberOfTeams: "32 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "spain 2")!), visitorFlagImage:  UIImage.imageWithBorder(from: UIImage(named: "netherlands")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "uruguay")!), finalDescription: "Spain🥇 - Netherlands🥈 1:0 (a.e.t)", thirdPlaceDescription: "Germany🥉 - Uruguay 3:2", topScorer: "Golden Boot: Thommas Muller 🇩🇪 5 goals", mvp: "Golden Ball: Diego Forlán 🇺🇾", goldenGlove: "Golden Glove: Iker Casillas 🇪🇸", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "2014 🇧🇷", numberOfTeams: "32 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "germany 2")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "argentina")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "netherlands")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "brazil")!), finalDescription: "Germany🥇 - Argentina🥈 1:0 (a.e.t)", thirdPlaceDescription: "Netherlands🥉 - Brazil 3:0", topScorer: "Golden Boot: James Rodríguez 🇨🇴 6 goals", mvp: "Golden Ball: Lionel Messi 🇦🇷", goldenGlove: "Golden Glove: Manuel Neuer 🇩🇪", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "2018 🇷🇺", numberOfTeams: "32 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "france")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "croatia")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "belgium")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "england")!), finalDescription: "France🥇 - Croatia🥈 4:2", thirdPlaceDescription: "Belgium🥉 - England 2:0", topScorer: "Golden Boot: Harry Kane 🏴󠁧󠁢󠁥󠁮󠁧󠁿 6 goals", mvp: "Golden Ball: Luka Modrić 🇭🇷", goldenGlove: "Golden Glove: Thibaut Courtois 🇧🇪", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "2022 🇶🇦", numberOfTeams: "32 teams participated", homeFlagImage: UIImage.imageWithBorder(from: UIImage(named: "argentina")!), visitorFlagImage: UIImage.imageWithBorder(from: UIImage(named: "france")!), thirdPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "croatia")!), fourthPlaceFlagImage: UIImage.imageWithBorder(from: UIImage(named: "morocco")!), finalDescription: "Argentina🥇 - France🥈 3:3 (a.e.t) (5-3 p.)", thirdPlaceDescription: "Croatia🥉 - Morocco 2:1", topScorer: "Golden Boot: Kylian Mbappé 🇫🇷 8 goals", mvp: "Golden Ball: Lionel Messi 🇦🇷", goldenGlove: "Golden Glove: Emiliano Martínez 🇦🇷", finalLabelText: "Final", thirdPlaceLabelText: "Third place", versus: "-", secondVersus: "-"),
        
        WorldCupYear(year: "2026 🇨🇦 & 🇲🇽 & 🇺🇸", numberOfTeams: "", homeFlagImage: UIImage(), visitorFlagImage: UIImage(), thirdPlaceFlagImage: UIImage(), fourthPlaceFlagImage: UIImage(), finalDescription: "It will be the first tournament with 48 teams in a history", thirdPlaceDescription: "", topScorer: "", mvp: "", goldenGlove: "", finalLabelText: "", thirdPlaceLabelText: "", versus: "", secondVersus: "")
    ]
}
